### PR TITLE
feat: proper NgModule support for Angular

### PR DESCRIPTION
**Pull request by jogboms**

### CODE REVIEW

**Comment by jogboms** [comment]
@triniwiz figured this was necessary too. What do you think?

**Comment by triniwiz** [comment]
Looks good @jogboms you're on fire

**Comment by triniwiz** [comment]
How does the v13.x for ios look ?

**Comment by jogboms** [comment]
I figured i work on this PR first but i'd take a proper look at it today.

**Comment by triniwiz** [comment]
I thought about writing something from scratch for IOS

**Comment by jogboms** [comment]
Scratch right? I just don't fully understand my way around iOS specifics

**Comment by triniwiz** [comment]
@jogboms just say when

**Comment by jogboms** [comment]
@triniwiz do you plan on using the same Socket Library?

**Comment by triniwiz** [comment]
😂 i meant to merge but i'm currently working on a pusher plugin

**Comment by jogboms** [comment]
Oh! 🎉  Well, this PR is done and tested with demo files. Just that still no iOS support.

and no update on README 😧

**Comment by jogboms** [comment]
@triniwiz Its done now. 🤠

**Pull request merged**
