### PR TITLE
chore: dependency update, code review and clean up.

### PR DESCRIPTION
**Pull request by jogboms**

### CODE REVIEW

**Comment by triniwiz** [comment]
Nice update I started working on upgrading IOS to use the latest version but ran into some hiccups

**Comment by jogboms** [comment]
@triniwiz I'm looking into this right now. I would send a PR that should fix most of the IOS-related issues soon once i make head way.

- #44
- #42

**Comment by triniwiz** [comment]
I started working with v13.x of the ios pod but it was giving some connection problems

**Comment by jogboms** [comment]
@triniwiz Testing out with 11 first to avoid the breaking change warnings #49

**Comment by triniwiz** [comment]
12/13 i think are the currently supported version

**Comment by jogboms** [comment]
Really. I'd dig in.

**Pull request merged**
